// ============================================================
// Lesson 2 단어장 (마석고 2학년) — 86 단어
// 필드: no(번호) w(단어) p(품사) m(뜻) ex(예문)
//       f(파생어: [단어, 품사, 뜻, (0=퀴즈 출제 제외)])
//       note(참고 메모) fq:false(품사 변신 퀴즈에서 제외)
// ============================================================
window.VOCAB_LESSONS = window.VOCAB_LESSONS || [];
window.VOCAB_LESSONS.push({
  id: "L02",
  title: "Lesson 2",
  subtitle: "교과서 2과",
  words: [
    { no: 1, w: "subscription", p: "n.", m: "구독",
      ex: "The content on that channel became so stale that I canceled my subscription.",
      f: [["subscribe", "v.", "구독하다"], ["subscriber", "n.", "구독자"]] },
    { no: 2, w: "streaming", p: "n.", m: "스트리밍",
      ex: "The popularity of streaming services has led to a decline in traditional media industry.",
      f: [["stream", "v.", "흐르다, 스트리밍하다"]] },
    { no: 3, w: "utilize", p: "v.", m: "활용하다",
      ex: "We were encouraged to utilize online resources to enhance our language learning ability.",
      f: [["utilization", "n.", "활용, 이용"], ["utility", "n.", "유용(성)", 0]] },
    { no: 4, w: "expand", p: "v.", m: "확장하다",
      ex: "The apparel company plans to expand into new markets to strengthen its global position.",
      f: [["expansion", "n.", "확장, 팽창"]] },
    { no: 5, w: "latest", p: "a.", m: "최근의", fq: false,
      note: "late의 최상급은 두 가지예요 — latest(가장 최근의·시간), last(마지막의·순서). 68번 last와 비교해 보세요!",
      ex: "No matter how busy you are, keep me updated on the latest advances in your work.",
      f: [["late", "a.", "늦은 (원급)"], ["lately", "ad.", "최근에"], ["last", "a.", "마지막의 (late의 또 다른 최상급)", 0]] },
    { no: 6, w: "quality", p: "a.", m: "고급(양질)의, 좋은",
      ex: "The students will receive a quality education.",
      f: [["quality", "n.", "질, 품질 (같은 철자)"], ["qualify", "v.", "자격을 얻다(주다)"], ["qualification", "n.", "자격 (요건)", 0]] },
    { no: 7, w: "economic", p: "a.", m: "경제의",
      ex: "With the global economic downturn, the economic growth rate in Korea is also gradually slowing down.",
      f: [["economy", "n.", "경제"], ["economics", "n.", "경제학", 0], ["economical", "a.", "절약하는, 경제적인", 0], ["economist", "n.", "경제학자", 0]] },
    { no: 8, w: "take part in", p: "phr.", m: "참여하다",
      ex: "Numerous business organizations have expressed a desire to take part in the fundraiser.",
      f: [["participate (in)", "v.", "참여하다 (= take part in)"], ["participation", "n.", "참여"]] },
    { no: 9, w: "prioritize", p: "v.", m: "우선시하다",
      ex: "For working moms, it can be difficult to prioritize between parenting and work.",
      f: [["priority", "n.", "우선순위, 우선 사항"]] },
    { no: 10, w: "personalization", p: "n.", m: "개인화",
      ex: "Online stores are using personalization strategies to enhance their customers' shopping experience.",
      f: [["personalize", "v.", "개인화하다, 개인의 필요에 맞추다"], ["personal", "a.", "개인의"], ["personality", "n.", "성격, 개성", 0]] },
    { no: 11, w: "access", p: "n.", m: "접근",
      ex: "By subscribing to this service, you will have access to everything in the library.",
      f: [["access", "v.", "접근하다 (같은 철자)"], ["accessible", "a.", "접근(이용) 가능한"], ["accessibility", "n.", "접근성", 0]] },
    { no: 12, w: "benefit", p: "n.", m: "이익, 혜택",
      ex: "The new maternity policy will have real benefits for many couples.",
      f: [["benefit", "v.", "이익을 주다(얻다) (같은 철자)"], ["beneficial", "a.", "유익한, 이로운"]] },
    { no: 13, w: "via", p: "prep.", m: "~을 통해서",
      ex: "You can control the smart home devices via smartphone.",
      f: [] },
    { no: 14, w: "stable", p: "a.", m: "안정적인",
      ex: "The price of oil should remain stable for the rest of the year.",
      f: [["stability", "n.", "안정(성)"], ["stabilize", "v.", "안정시키다"]] },
    { no: 15, w: "revenue", p: "n.", m: "수익",
      ex: "The state's revenue soared after implementing the new tax policy.",
      f: [] },
    { no: 16, w: "loyalty", p: "n.", m: "충성심",
      ex: "The boss emphasizes that building customer loyalty requires consistent quality and exceptional service.",
      f: [["loyal", "a.", "충성스러운"]] },
    { no: 17, w: "a range of", p: "phr.", m: "~의 범위의",
      ex: "A wide range of colors and patterns are available.",
      f: [["range", "n.", "범위, 폭"], ["range (from A to B)", "v.", "(범위가 A에서 B에) 이르다", 0]] },
    { no: 18, w: "flexible", p: "a.", m: "융통성 있는",
      ex: "It is proved that flexible working hours promote employee satisfaction and productivity.",
      f: [["flexibility", "n.", "유연성, 융통성"], ["flexibly", "ad.", "유연하게", 0]] },
    { no: 19, w: "driver", p: "n.", m: "추진 요인, 동인",
      ex: "Consumers’ demand for eco-friendly products is a major driver for the sustainable future.",
      f: [["drive", "v.", "추진하다; 운전하다"]] },
    { no: 20, w: "relevant", p: "a.", m: "관련 있는, 적절한",
      ex: "If you find any relevant information, let me know immediately.",
      f: [["relevance", "n.", "관련(성)"]] },
    { no: 21, w: "attractive", p: "a.", m: "매력적인",
      ex: "What makes this chocolate so popular is its attractive packaging.",
      f: [["attract", "v.", "(마음을) 끌다"], ["attraction", "n.", "매력; 명소", 0]] },
    { no: 22, w: "requirement", p: "n.", m: "요구",
      ex: "Manager positions have specific requirements, including 3 years of experience and qualifications.",
      f: [["require", "v.", "요구하다, 필요로 하다"], ["required", "a.", "필수의"]] },
    { no: 23, w: "ownership", p: "n.", m: "소유권",
      ex: "There is an ongoing legal battle over the ownership of this land.",
      f: [["own", "v.", "소유하다"], ["owner", "n.", "소유자, 주인", 0]] },
    { no: 24, w: "disc", p: "n.", m: "디스크",
      ex: "Recordings of the instructor's talks are also available on disc.",
      f: [] },
    { no: 25, w: "customization", p: "n.", m: "고객맞춤화",
      ex: "This new software offers unique customization options that allow you to adapt to your preferences.",
      f: [["customize", "v.", "주문 제작하다, 맞춤화하다"], ["customized", "a.", "맞춤형의", 0], ["customer", "n.", "고객", 0]] },
    { no: 26, w: "preference", p: "n.", m: "선호",
      ex: "Many students expressed a preference for new policies rather than old ones.",
      f: [["prefer", "v.", "선호하다"], ["preferable", "a.", "더 좋은, 선호되는"]] },
    { no: 27, w: "generation", p: "n.", m: "세대",
      ex: "Cultural differences between generations can sometimes result in conflict in the office.",
      f: [["generate", "v.", "발생시키다, 만들어 내다"]] },
    { no: 28, w: "uniqueness", p: "n.", m: "고유성",
      ex: "The idol group succeeded with a strategy that focused on the uniqueness of each member.",
      f: [["unique", "a.", "고유한, 독특한"], ["uniquely", "ad.", "독특하게", 0]] },
    { no: 29, w: "thoroughly", p: "ad.", m: "철저히, 대단히",
      ex: "Detectives thoroughly investigate even the smallest clues to solve crimes.",
      f: [["thorough", "a.", "철저한"]] },
    { no: 30, w: "specialized", p: "a.", m: "전문화된",
      ex: "As society becomes increasingly decentralized and sophisticated, it demands specialized services.",
      f: [["specialize (in)", "v.", "전문으로 하다"], ["specialist", "n.", "전문가"], ["specialty", "n.", "전문 (분야)", 0]] },
    { no: 31, w: "address", p: "v.", m: "다루다, 처리하다",
      ex: "We worked together to address the issue, finding the best solution that satisfied all.",
      f: [["address", "n.", "주소; 연설 (같은 철자)"]] },
    { no: 32, w: "concern", p: "n.", m: "걱정, 우려",
      ex: "My friend's concern about the project's deadline made us work hard to finish it on time.",
      f: [["concern", "v.", "걱정시키다; 관련되다 (같은 철자)"], ["concerned", "a.", "걱정하는"], ["concerning", "prep.", "~에 관한", 0]] },
    { no: 33, w: "uniform", p: "a.", m: "획일적인",
      ex: "This store is popular because it sells everything at a uniform price.",
      f: [["uniform", "n.", "제복, 교복 (같은 철자)"], ["uniformity", "n.", "획일성, 균일성"]] },
    { no: 34, w: "convenience", p: "n.", m: "편의성",
      ex: "Convenience of purchase is one of the most important things consumers look for when buying something.",
      f: [["convenient", "a.", "편리한"], ["conveniently", "ad.", "편리하게", 0]] },
    { no: 35, w: "adjust", p: "v.", m: "조정하다",
      ex: "I'll adjust my schedule so you can join the meeting.",
      f: [["adjustment", "n.", "조정, 수정"], ["adjustable", "a.", "조절 가능한", 0]] },
    { no: 36, w: "fee", p: "n.", m: "요금, 수수료",
      ex: "The museum has a lot of artifacts despite the fact that there is no admission fee.",
      f: [] },
    { no: 37, w: "enhance", p: "v.", m: "향상시키다",
      ex: "To enhance your foreign language skills, it's important to study consistently.",
      f: [["enhancement", "n.", "향상, 개선"]] },
    { no: 38, w: "device", p: "n.", m: "장치, 기기",
      ex: "Today, people around the world rely on electronic devices to stay connected to the world around them.",
      f: [["devise", "v.", "고안하다, 궁리하다"]] },
    { no: 39, w: "center on", p: "phr.", m: "~에 초점을 맞추다",
      ex: "His artwork centers on environmental and animal protection.",
      f: [["center", "n.", "중심"], ["central", "a.", "중심의, 중심적인"]] },
    { no: 40, w: "numerous", p: "a.", m: "많은",
      ex: "He has always attracted numerous fans with his skill and personality.",
      f: [["number", "n.", "수, 숫자"]] },
    { no: 41, w: "with ease", p: "phr.", m: "쉽게",
      ex: "This actor has the ability to take on any role and make it his own with ease.",
      f: [["ease", "n.", "쉬움, 용이함"], ["easy", "a.", "쉬운"], ["easily", "ad.", "쉽게 (= with ease)", 0]] },
    { no: 42, w: "have no choice but to", p: "phr.", m: "~할 수 밖에 없다",
      ex: "Since I had the flu, I had no choice but to join the meeting online.",
      f: [["choice", "n.", "선택"], ["choose", "v.", "선택하다"]] },
    { no: 43, w: "algorithm", p: "n.", m: "알고리즘",
      ex: "The new algorithm has improved the performance of our software tremendously.",
      f: [] },
    { no: 44, w: "identify", p: "v.", m: "확인하다",
      ex: "Before approaching this question, it's important to identify what the questioner's intent is.",
      f: [["identification", "n.", "(신원) 확인; 신분증"], ["identity", "n.", "신분, 정체", 0], ["identical", "a.", "동일한, 똑같은"]] },
    { no: 45, w: "satisfaction", p: "n.", m: "만족(감), 흡족",
      ex: "The boy felt a sense of satisfaction each time he completes a robot model.",
      f: [["satisfy", "v.", "만족시키다"], ["satisfied", "a.", "만족한", 0], ["satisfying", "a.", "만족감을 주는", 0], ["satisfactory", "a.", "만족스러운, (기준에) 충분한", 0]] },
    { no: 46, w: "recommend", p: "v.", m: "추천하다",
      ex: "When you go to a foreign country, I recommend always trying food that is unique to that country.",
      f: [["recommendation", "n.", "추천"]] },
    { no: 47, w: "potential", p: "n.", m: "잠재력",
      ex: "From an early age, he showed the potential to be a world-class soccer player.",
      f: [["potential", "a.", "잠재적인, 가능성 있는 (같은 철자)"], ["potentially", "ad.", "잠재적으로"]] },
    { no: 48, w: "overconsumption", p: "n.", m: "소비과잉",
      ex: "Fast fashion is not only causing overconsumption of clothes, but also environmental problems.",
      f: [["consume", "v.", "소비하다"], ["consumption", "n.", "소비", 0], ["consumer", "n.", "소비자", 0]] },
    { no: 49, w: "multiple", p: "a.", m: "많은, 다수의",
      ex: "He suffered multiple injuries in the accident.",
      f: [["multiply", "v.", "크게 늘리다; 곱하다"]] },
    { no: 50, w: "excessive", p: "a.", m: "지나친, 과도한",
      ex: "It's not right to put excessive pressure on your child to study.",
      f: [["exceed", "v.", "초과하다, 넘다"], ["excess", "n.", "과잉, 지나침", 0]] },
    { no: 51, w: "financial", p: "a.", m: "금융의, 재정의",
      ex: "To better utilize the company's budget, we brought on a new financial analyst.",
      f: [["finance", "n.", "재정, 금융"], ["financially", "ad.", "재정적으로", 0]] },
    { no: 52, w: "burden", p: "n.", m: "부담, 짐",
      ex: "Every parent in the world carries the heavy burden of responsibility for their children.",
      f: [["burden", "v.", "부담을 지우다 (같은 철자)"], ["burdensome", "a.", "부담스러운"]] },
    { no: 53, w: "affordable", p: "a.", m: "감당할 수 있는",
      ex: "They couldn't find any affordable houses for them.",
      f: [["afford", "v.", "~할 (금전적·시간적) 여유가 있다"]] },
    { no: 54, w: "consider", p: "v.", m: "고려하다",
      ex: "We should consider all possible options before making a decision.",
      f: [["consideration", "n.", "고려, 숙고"], ["considerable", "a.", "상당한", 0], ["considerate", "a.", "사려 깊은", 0]] },
    { no: 55, w: "strain", p: "n.", m: "부담, 압박",
      ex: "My sister is under tremendous strain for her tests.",
      f: [["strain", "v.", "혹사하다; 잡아당기다 (같은 철자)"]] },
    { no: 56, w: "cancel", p: "v.", m: "취소하다",
      ex: "Due to extreme weather, we're canceling the picnic scheduled for today.",
      f: [["cancellation", "n.", "취소"]] },
    { no: 57, w: "beneficial", p: "a.", m: "유익한, 이로운",
      ex: "Regular exercise has many beneficial effects on both physical and mental health.",
      f: [["benefit", "n.", "이익, 혜택"], ["benefit", "v.", "이익을 주다(얻다)", 0]] },
    { no: 58, w: "additionally", p: "ad.", m: "게다가",
      ex: "Additionally, the number of people who lived in every country was much smaller than it is today.",
      f: [["add", "v.", "더하다, 추가하다"], ["additional", "a.", "추가의"], ["addition", "n.", "추가; 덧셈", 0]] },
    { no: 59, w: "packaging", p: "n.", m: "포장",
      ex: "The boss decided to change the packaging on two of our key products.",
      f: [["package", "n.", "소포, 포장물"], ["pack", "v.", "(짐을) 싸다, 포장하다"]] },
    { no: 60, w: "disposable", p: "a.", m: "일회용의",
      ex: "A souvenir shop is selling disposable cameras.",
      f: [["dispose (of)", "v.", "처리하다, (~을) 버리다"], ["disposal", "n.", "처리, 폐기", 0]] },
    { no: 61, w: "opt for", p: "phr.", m: "~을 선택하다",
      ex: "There are several options on the menu, but I think I'll opt for the vegan one.",
      f: [["option", "n.", "선택(권), 선택 사항"], ["optional", "a.", "선택적인"]] },
    { no: 62, w: "embedded", p: "a.", m: "내포된, (마음 속에 깊이) 새겨진",
      ex: "Mistrust of each other is deeply embedded, leading to gender conflict in society.",
      f: [["embed", "v.", "(단단히) 끼워 넣다, 깊이 새기다"]] },
    { no: 63, w: "continuously", p: "ad.", m: "연달아, 끊임없이",
      ex: "Not content with passing the exam, he set new goals to continuously grow.",
      f: [["continue", "v.", "계속하다"], ["continuous", "a.", "끊임없는, 계속되는"]] },
    { no: 64, w: "conduct", p: "v.", m: "(특정한 활동을) 하다",
      note: "동사는 conDUCT(뒤 강세), 명사는 CONduct(앞 강세)로 발음해요.",
      ex: "Conducting a survey is an important step in advancing social knowledge.",
      f: [["conduct", "n.", "행동, 수행 (같은 철자)"], ["conductor", "n.", "지휘자; (전기) 전도체"]] },
    { no: 65, w: "psychology", p: "n.", m: "심리학",
      ex: "I double majored in evolutionary psychology and business administration in college.",
      f: [["psychological", "a.", "심리적인, 심리학의"], ["psychologist", "n.", "심리학자", 0]] },
    { no: 66, w: "conclusion", p: "n.", m: "결론",
      ex: "After 10 hours of negotiations, the two parties reached a conclusion.",
      f: [["conclude", "v.", "결론을 내리다; 끝내다"], ["conclusive", "a.", "결정적인", 0]] },
    { no: 67, w: "assume", p: "v.", m: "추정하다",
      ex: "Our team is so strong that we assume we're going to win this World Cup.",
      f: [["assumption", "n.", "추정, 가정"]] },
    { no: 68, w: "last", p: "v.", m: "지속되다",
      note: "last는 형용사로 '마지막의', 동사로 '지속되다'의 뜻이 있어요.",
      ex: "How many hours does the musical you're going to see today last?",
      f: [["lasting", "a.", "지속적인, 오래가는"], ["last", "a.", "마지막의; 지난 (같은 철자)", 0], ["late", "a.", "늦은", 0], ["latest", "a.", "최근의 (5번 참고)", 0]] },
    { no: 69, w: "fade", p: "v.", m: "서서히 사라지다",
      ex: "Her smile faded away, disappearing without a trace.",
      f: [["faded", "a.", "빛바랜, 시든"]] },
    { no: 70, w: "critical", p: "a.", m: "중요한",
      ex: "This painting captures one of the most critical moments in the history of the Joseon Dynasty.",
      f: [["criticize", "v.", "비판하다"], ["criticism", "n.", "비판, 비평"], ["critic", "n.", "비평가", 0]] },
    { no: 71, w: "possession", p: "n.", m: "소유",
      ex: "The older I get, the more I realize the truth that having possession doesn't always lead to happiness.",
      f: [["possess", "v.", "소유하다"]] },
    { no: 72, w: "novel", p: "a.", m: "새로운",
      note: "명사 novel(소설)과 철자가 같아요. '새로운'이라는 형용사 뜻도 꼭 기억하세요!",
      ex: "Her approach to the problem was novel and brought a new perspective to an old challenge.",
      f: [["novel", "n.", "소설 (같은 철자)"], ["novelty", "n.", "새로움, 참신함"]] },
    { no: 73, w: "norm", p: "n.", m: "표준, 일반적인 것",
      ex: "Over time, things that were once considered unique gradually become the norm.",
      f: [["normal", "a.", "보통의, 정상적인"], ["normally", "ad.", "보통, 정상적으로", 0]] },
    { no: 74, w: "raise the bar", p: "phr.", m: "기대치를 높이다",
      ex: "You don't need to push yourself too hard, but you do need to raise the bar a bit on your goals.",
      f: [["raise", "v.", "(들어) 올리다; 기르다 (타동사)"], ["rise", "v.", "오르다 (자동사, 목적어 없음)", 0]] },
    { no: 75, w: "purchase", p: "n.", m: "구매",
      ex: "Bring in this coupon and we'll give you a free drink with your next purchase.",
      f: [["purchase", "v.", "구매하다 (같은 철자)"]] },
    { no: 76, w: "expectation", p: "n.", m: "기대, 예상",
      ex: "The team's performance lived up to everyone's expectations.",
      f: [["expect", "v.", "기대하다, 예상하다"], ["expected", "a.", "예상되는", 0], ["unexpected", "a.", "예상치 못한", 0]] },
    { no: 77, w: "get used to", p: "phr.", m: "~에 익숙하다",
      note: "be/get used to + (동)명사: ~에 익숙하다(익숙해지다) / used to + 동사원형: (예전에) ~하곤 했다",
      ex: "It takes time to get used to a new position.",
      f: [["be used to + (동)명사", "", "~에 익숙하다"], ["used to + 동사원형", "", "(예전에) ~하곤 했다"]] },
    { no: 78, w: "stimulate", p: "v.", m: "자극하다",
      ex: "Appropriate videos that are relevant to the lesson will help stimulate students' interest.",
      f: [["stimulation", "n.", "자극"], ["stimulus", "n.", "자극(제) (복수형 stimuli)", 0]] },
    { no: 79, w: "thrilled", p: "a.", m: "황홀해 하는, 아주 흥분한",
      ex: "The idol group was thrilled by the audience's enthusiastic cheers.",
      f: [["thrill", "n.", "전율, 스릴, 흥분"], ["thrilling", "a.", "아주 신나는, 짜릿한", 0]] },
    { no: 80, w: "identity", p: "n.", m: "신분, 정체",
      ex: "Please provide something to prove your identity.",
      f: [["identify", "v.", "(신원 등을) 확인하다"], ["identical", "a.", "동일한, 똑같은", 0]] },
    { no: 81, w: "accumulation", p: "n.", m: "축적",
      ex: "His accumulation of wealth comes from success in travel-related business platforms.",
      f: [["accumulate", "v.", "축적하다, 모으다"]] },
    { no: 82, w: "material", p: "a.", m: "물질적인",
      ex: "Her material possessions, like luxurious car and house, reflect her wealth.",
      f: [["material", "n.", "재료, 소재 (같은 철자)"], ["materialism", "n.", "물질주의"]] },
    { no: 83, w: "goods", p: "n.", m: "상품", fq: false,
      note: "'상품'의 뜻일 때는 항상 복수형(goods)으로 써요.",
      ex: "These goods are priced too high.",
      f: [["good", "a.", "좋은"]] },
    { no: 84, w: "connected to", p: "phr.", m: "관련이 있는",
      ex: "Her love for animals is deeply connected to her decision to become a veterinarian.",
      f: [["connect", "v.", "연결하다"], ["connection", "n.", "연결, 관련"]] },
    { no: 85, w: "nonetheless", p: "ad.", m: "그럼에도 불구하고",
      ex: "We were burnt out; nonetheless, we pushed ourselves to finish the project before the deadline.",
      f: [["nevertheless", "ad.", "그럼에도 불구하고 (동의어)", 0]] },
    { no: 86, w: "sum", p: "n.", m: "합, 총계", fq: false,
      ex: "The sum of the sales figures for this quarter exceeds our expectations.",
      f: [["sum up", "phr.", "요약하다; 합산하다"], ["summary", "n.", "요약"], ["summarize", "v.", "요약하다", 0]] }
  ]
});
